"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_cancellation_policy_list import InlineResponse2003PropertyCancellationPolicyList
from lodgea-python.model.inline_response2003_property_fee_policy_list import InlineResponse2003PropertyFeePolicyList
from lodgea-python.model.inline_response2003_property_guarantee_policy import InlineResponse2003PropertyGuaranteePolicy
from lodgea-python.model.inline_response2003_property_pets_policy import InlineResponse2003PropertyPetsPolicy
from lodgea-python.model.inline_response2003_property_tax_policy_list import InlineResponse2003PropertyTaxPolicyList
globals()['InlineResponse2003PropertyCancellationPolicyList'] = InlineResponse2003PropertyCancellationPolicyList
globals()['InlineResponse2003PropertyFeePolicyList'] = InlineResponse2003PropertyFeePolicyList
globals()['InlineResponse2003PropertyGuaranteePolicy'] = InlineResponse2003PropertyGuaranteePolicy
globals()['InlineResponse2003PropertyPetsPolicy'] = InlineResponse2003PropertyPetsPolicy
globals()['InlineResponse2003PropertyTaxPolicyList'] = InlineResponse2003PropertyTaxPolicyList
from lodgea-python.model.inline_response2003_property_policy_list import InlineResponse2003PropertyPolicyList


class TestInlineResponse2003PropertyPolicyList(unittest.TestCase):
    """InlineResponse2003PropertyPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyPolicyList(self):
        """Test InlineResponse2003PropertyPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
