"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_record_modified import PropertiesPropertyIdGet200ResponsePropertyRecordModified


class TestPropertiesPropertyIdGet200ResponsePropertyRecordModified(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyRecordModified unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyRecordModified(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyRecordModified"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyRecordModified()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
