"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2001_geo import InlineResponse2001Geo
from lodgea-python.model.inline_response2003_property_award_list import InlineResponse2003PropertyAwardList
from lodgea-python.model.inline_response2003_property_cancellation_grace_period import InlineResponse2003PropertyCancellationGracePeriod
from lodgea-python.model.inline_response2003_property_contact_list import InlineResponse2003PropertyContactList
from lodgea-python.model.inline_response2003_property_facility_info import InlineResponse2003PropertyFacilityInfo
from lodgea-python.model.inline_response2003_property_guest_info import InlineResponse2003PropertyGuestInfo
from lodgea-python.model.inline_response2003_property_media_list import InlineResponse2003PropertyMediaList
from lodgea-python.model.inline_response2003_property_policy_list import InlineResponse2003PropertyPolicyList
from lodgea-python.model.inline_response2003_property_property_info import InlineResponse2003PropertyPropertyInfo
from lodgea-python.model.inline_response2003_property_record_created import InlineResponse2003PropertyRecordCreated
from lodgea-python.model.inline_response2003_property_record_modified import InlineResponse2003PropertyRecordModified
from lodgea-python.model.inline_response2003_property_service_list import InlineResponse2003PropertyServiceList
globals()['InlineResponse2001Geo'] = InlineResponse2001Geo
globals()['InlineResponse2003PropertyAwardList'] = InlineResponse2003PropertyAwardList
globals()['InlineResponse2003PropertyCancellationGracePeriod'] = InlineResponse2003PropertyCancellationGracePeriod
globals()['InlineResponse2003PropertyContactList'] = InlineResponse2003PropertyContactList
globals()['InlineResponse2003PropertyFacilityInfo'] = InlineResponse2003PropertyFacilityInfo
globals()['InlineResponse2003PropertyGuestInfo'] = InlineResponse2003PropertyGuestInfo
globals()['InlineResponse2003PropertyMediaList'] = InlineResponse2003PropertyMediaList
globals()['InlineResponse2003PropertyPolicyList'] = InlineResponse2003PropertyPolicyList
globals()['InlineResponse2003PropertyPropertyInfo'] = InlineResponse2003PropertyPropertyInfo
globals()['InlineResponse2003PropertyRecordCreated'] = InlineResponse2003PropertyRecordCreated
globals()['InlineResponse2003PropertyRecordModified'] = InlineResponse2003PropertyRecordModified
globals()['InlineResponse2003PropertyServiceList'] = InlineResponse2003PropertyServiceList
from lodgea-python.model.inline_response2003_property import InlineResponse2003Property


class TestInlineResponse2003Property(unittest.TestCase):
    """InlineResponse2003Property unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003Property(self):
        """Test InlineResponse2003Property"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003Property()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
