"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2004_rate_plan_list import InlineResponse2004RatePlanList
globals()['InlineResponse2004RatePlanList'] = InlineResponse2004RatePlanList
from lodgea-python.model.inline_response2004_availability_list import InlineResponse2004AvailabilityList


class TestInlineResponse2004AvailabilityList(unittest.TestCase):
    """InlineResponse2004AvailabilityList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004AvailabilityList(self):
        """Test InlineResponse2004AvailabilityList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004AvailabilityList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
