"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_operation_time_list import InlineResponse2003PropertyOperationTimeList


class TestInlineResponse2003PropertyOperationTimeList(unittest.TestCase):
    """InlineResponse2003PropertyOperationTimeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyOperationTimeList(self):
        """Test InlineResponse2003PropertyOperationTimeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyOperationTimeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
