"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.location_search_post400_response_validation_errors_inner import LocationSearchPost400ResponseValidationErrorsInner
globals()['LocationSearchPost400ResponseValidationErrorsInner'] = LocationSearchPost400ResponseValidationErrorsInner
from lodgea-python.model.location_search_post400_response import LocationSearchPost400Response


class TestLocationSearchPost400Response(unittest.TestCase):
    """LocationSearchPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationSearchPost400Response(self):
        """Test LocationSearchPost400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocationSearchPost400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
