"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_attraction_list_inner import AvailablePropertiesInner1AttractionListInner
from lodgea-python.model.available_properties_inner1_geo import AvailablePropertiesInner1Geo
from lodgea-python.model.available_properties_inner1_lowest_price import AvailablePropertiesInner1LowestPrice
from lodgea-python.model.available_properties_inner1_media_list_inner import AvailablePropertiesInner1MediaListInner
globals()['AvailablePropertiesInner1AttractionListInner'] = AvailablePropertiesInner1AttractionListInner
globals()['AvailablePropertiesInner1Geo'] = AvailablePropertiesInner1Geo
globals()['AvailablePropertiesInner1LowestPrice'] = AvailablePropertiesInner1LowestPrice
globals()['AvailablePropertiesInner1MediaListInner'] = AvailablePropertiesInner1MediaListInner
from lodgea-python.model.available_properties_inner1 import AvailablePropertiesInner1


class TestAvailablePropertiesInner1(unittest.TestCase):
    """AvailablePropertiesInner1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePropertiesInner1(self):
        """Test AvailablePropertiesInner1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailablePropertiesInner1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
