"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2001_attraction_list import InlineResponse2001AttractionList
from lodgea-python.model.inline_response2001_geo import InlineResponse2001Geo
from lodgea-python.model.inline_response2001_lowest_price import InlineResponse2001LowestPrice
from lodgea-python.model.inline_response2001_media_list import InlineResponse2001MediaList
globals()['InlineResponse2001AttractionList'] = InlineResponse2001AttractionList
globals()['InlineResponse2001Geo'] = InlineResponse2001Geo
globals()['InlineResponse2001LowestPrice'] = InlineResponse2001LowestPrice
globals()['InlineResponse2001MediaList'] = InlineResponse2001MediaList
from lodgea-python.model.inline_response2001_list import InlineResponse2001List


class TestInlineResponse2001List(unittest.TestCase):
    """InlineResponse2001List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001List(self):
        """Test InlineResponse2001List"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001List()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
