"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.v1_property_list_post200_response_list_inner import V1PropertyListPost200ResponseListInner


class TestV1PropertyListPost200ResponseListInner(unittest.TestCase):
    """V1PropertyListPost200ResponseListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PropertyListPost200ResponseListInner(self):
        """Test V1PropertyListPost200ResponseListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1PropertyListPost200ResponseListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
