"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.v1_availability_get_post200_response_room_type_list_inner import V1AvailabilityGetPost200ResponseRoomTypeListInner


class TestV1AvailabilityGetPost200ResponseRoomTypeListInner(unittest.TestCase):
    """V1AvailabilityGetPost200ResponseRoomTypeListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AvailabilityGetPost200ResponseRoomTypeListInner(self):
        """Test V1AvailabilityGetPost200ResponseRoomTypeListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AvailabilityGetPost200ResponseRoomTypeListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
