"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2004_pricing_list import InlineResponse2004PricingList


class TestInlineResponse2004PricingList(unittest.TestCase):
    """InlineResponse2004PricingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004PricingList(self):
        """Test InlineResponse2004PricingList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004PricingList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
