"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_award_list import InlineResponse2003PropertyAwardList


class TestInlineResponse2003PropertyAwardList(unittest.TestCase):
    """InlineResponse2003PropertyAwardList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyAwardList(self):
        """Test InlineResponse2003PropertyAwardList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyAwardList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
