"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response400_validation_errors import InlineResponse400ValidationErrors
globals()['InlineResponse400ValidationErrors'] = InlineResponse400ValidationErrors
from lodgea-python.model.inline_response400 import InlineResponse400


class TestInlineResponse400(unittest.TestCase):
    """InlineResponse400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400(self):
        """Test InlineResponse400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
