"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2001_geo_location import InlineResponse2001GeoLocation
globals()['InlineResponse2001GeoLocation'] = InlineResponse2001GeoLocation
from lodgea-python.model.inline_response2001_geo import InlineResponse2001Geo


class TestInlineResponse2001Geo(unittest.TestCase):
    """InlineResponse2001Geo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Geo(self):
        """Test InlineResponse2001Geo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001Geo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
