"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_geo_location import AvailablePropertiesInner1GeoLocation
from lodgea-python.model.properties_property_id_get200_response_property_property_info_accepted_payment_list_inner import PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner
from lodgea-python.model.properties_property_id_get200_response_property_property_info_message_list_inner import PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner
globals()['AvailablePropertiesInner1GeoLocation'] = AvailablePropertiesInner1GeoLocation
globals()['PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner'] = PropertiesPropertyIdGet200ResponsePropertyPropertyInfoAcceptedPaymentListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner'] = PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner
from lodgea-python.model.properties_property_id_get200_response_property_property_info import PropertiesPropertyIdGet200ResponsePropertyPropertyInfo


class TestPropertiesPropertyIdGet200ResponsePropertyPropertyInfo(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyPropertyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyPropertyInfo(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyPropertyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyPropertyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
