"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2004_availability_list import InlineResponse2004AvailabilityList
globals()['InlineResponse2004AvailabilityList'] = InlineResponse2004AvailabilityList
from lodgea-python.model.inline_response2004 import InlineResponse2004


class TestInlineResponse2004(unittest.TestCase):
    """InlineResponse2004 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004(self):
        """Test InlineResponse2004"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
