"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_operation_time_list import InlineResponse2003PropertyOperationTimeList
globals()['InlineResponse2003PropertyOperationTimeList'] = InlineResponse2003PropertyOperationTimeList
from lodgea-python.model.inline_response2003_property_service_list import InlineResponse2003PropertyServiceList


class TestInlineResponse2003PropertyServiceList(unittest.TestCase):
    """InlineResponse2003PropertyServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyServiceList(self):
        """Test InlineResponse2003PropertyServiceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyServiceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
