"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_geo import AvailablePropertiesInner1Geo
from lodgea-python.model.properties_property_id_get200_response_property_award_list_inner import PropertiesPropertyIdGet200ResponsePropertyAwardListInner
from lodgea-python.model.properties_property_id_get200_response_property_cancellation_grace_period import PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
from lodgea-python.model.properties_property_id_get200_response_property_contact_list_inner import PropertiesPropertyIdGet200ResponsePropertyContactListInner
from lodgea-python.model.properties_property_id_get200_response_property_facility_info import PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_media_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
from lodgea-python.model.properties_property_id_get200_response_property_guest_info import PropertiesPropertyIdGet200ResponsePropertyGuestInfo
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInner
from lodgea-python.model.properties_property_id_get200_response_property_property_info import PropertiesPropertyIdGet200ResponsePropertyPropertyInfo
from lodgea-python.model.properties_property_id_get200_response_property_record_created import PropertiesPropertyIdGet200ResponsePropertyRecordCreated
from lodgea-python.model.properties_property_id_get200_response_property_record_modified import PropertiesPropertyIdGet200ResponsePropertyRecordModified
from lodgea-python.model.properties_property_id_get200_response_property_service_list_inner import PropertiesPropertyIdGet200ResponsePropertyServiceListInner
globals()['AvailablePropertiesInner1Geo'] = AvailablePropertiesInner1Geo
globals()['PropertiesPropertyIdGet200ResponsePropertyAwardListInner'] = PropertiesPropertyIdGet200ResponsePropertyAwardListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod'] = PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
globals()['PropertiesPropertyIdGet200ResponsePropertyContactListInner'] = PropertiesPropertyIdGet200ResponsePropertyContactListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfo'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyGuestInfo'] = PropertiesPropertyIdGet200ResponsePropertyGuestInfo
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInner'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyPropertyInfo'] = PropertiesPropertyIdGet200ResponsePropertyPropertyInfo
globals()['PropertiesPropertyIdGet200ResponsePropertyRecordCreated'] = PropertiesPropertyIdGet200ResponsePropertyRecordCreated
globals()['PropertiesPropertyIdGet200ResponsePropertyRecordModified'] = PropertiesPropertyIdGet200ResponsePropertyRecordModified
globals()['PropertiesPropertyIdGet200ResponsePropertyServiceListInner'] = PropertiesPropertyIdGet200ResponsePropertyServiceListInner
from lodgea-python.model.properties_property_id_get200_response_property import PropertiesPropertyIdGet200ResponseProperty


class TestPropertiesPropertyIdGet200ResponseProperty(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponseProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponseProperty(self):
        """Test PropertiesPropertyIdGet200ResponseProperty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponseProperty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
