"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2001_distance import InlineResponse2001Distance
globals()['InlineResponse2001Distance'] = InlineResponse2001Distance
from lodgea-python.model.inline_response2001_attraction_list import InlineResponse2001AttractionList


class TestInlineResponse2001AttractionList(unittest.TestCase):
    """InlineResponse2001AttractionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001AttractionList(self):
        """Test InlineResponse2001AttractionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001AttractionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
