"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_property_info_message_list_inner import PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner


class TestPropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyPropertyInfoMessageListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
