"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_attraction_list_inner_distance import AvailablePropertiesInner1AttractionListInnerDistance
globals()['AvailablePropertiesInner1AttractionListInnerDistance'] = AvailablePropertiesInner1AttractionListInnerDistance
from lodgea-python.model.available_properties_inner1_attraction_list_inner import AvailablePropertiesInner1AttractionListInner


class TestAvailablePropertiesInner1AttractionListInner(unittest.TestCase):
    """AvailablePropertiesInner1AttractionListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePropertiesInner1AttractionListInner(self):
        """Test AvailablePropertiesInner1AttractionListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailablePropertiesInner1AttractionListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
