"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.availability_search_post_request import AvailabilitySearchPostRequest


class TestAvailabilitySearchPostRequest(unittest.TestCase):
    """AvailabilitySearchPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailabilitySearchPostRequest(self):
        """Test AvailabilitySearchPostRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailabilitySearchPostRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
