"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.v1_availability_get_post200_response_rate_plan_list_inner_pricing_list_inner_price_list import V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList
globals()['V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList'] = V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInnerPriceList
from lodgea-python.model.v1_availability_get_post200_response_rate_plan_list_inner_pricing_list_inner import V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner


class TestV1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner(unittest.TestCase):
    """V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner(self):
        """Test V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AvailabilityGetPost200ResponseRatePlanListInnerPricingListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
