"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1 import AvailablePropertiesInner1
globals()['AvailablePropertiesInner1'] = AvailablePropertiesInner1
from lodgea-python.model.availability_search_post200_response import AvailabilitySearchPost200Response


class TestAvailabilitySearchPost200Response(unittest.TestCase):
    """AvailabilitySearchPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailabilitySearchPost200Response(self):
        """Test AvailabilitySearchPost200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailabilitySearchPost200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
