"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_product_list_inner import PropertiesPropertyIdGet200ResponseProductListInner
from lodgea-python.model.properties_property_id_get200_response_property import PropertiesPropertyIdGet200ResponseProperty
globals()['PropertiesPropertyIdGet200ResponseProductListInner'] = PropertiesPropertyIdGet200ResponseProductListInner
globals()['PropertiesPropertyIdGet200ResponseProperty'] = PropertiesPropertyIdGet200ResponseProperty
from lodgea-python.model.properties_property_id_get200_response import PropertiesPropertyIdGet200Response


class TestPropertiesPropertyIdGet200Response(unittest.TestCase):
    """PropertiesPropertyIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200Response(self):
        """Test PropertiesPropertyIdGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
