"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_get200_response_list_inner import PropertiesGet200ResponseListInner
globals()['PropertiesGet200ResponseListInner'] = PropertiesGet200ResponseListInner
from lodgea-python.model.properties_get200_response import PropertiesGet200Response


class TestPropertiesGet200Response(unittest.TestCase):
    """PropertiesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesGet200Response(self):
        """Test PropertiesGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
