"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response4001_validation_errors import InlineResponse4001ValidationErrors


class TestInlineResponse4001ValidationErrors(unittest.TestCase):
    """InlineResponse4001ValidationErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4001ValidationErrors(self):
        """Test InlineResponse4001ValidationErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse4001ValidationErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
