"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner_cancellation_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner_fee_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner_guarantee_policy import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner_pets_policy import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner_tax_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerCancellationPolicyListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerGuaranteePolicy
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerPetsPolicy
globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInner


class TestPropertiesPropertyIdGet200ResponsePropertyPolicyListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyPolicyListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyPolicyListInner(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyPolicyListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyPolicyListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
