"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_get200_response_list_inner import PropertiesGet200ResponseListInner


class TestPropertiesGet200ResponseListInner(unittest.TestCase):
    """PropertiesGet200ResponseListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesGet200ResponseListInner(self):
        """Test PropertiesGet200ResponseListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesGet200ResponseListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
