"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_availability_get200_response_availability_list_inner import PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
globals()['PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner'] = PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
from lodgea-python.model.properties_property_id_availability_get200_response import PropertiesPropertyIdAvailabilityGet200Response


class TestPropertiesPropertyIdAvailabilityGet200Response(unittest.TestCase):
    """PropertiesPropertyIdAvailabilityGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdAvailabilityGet200Response(self):
        """Test PropertiesPropertyIdAvailabilityGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdAvailabilityGet200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
