"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner import AvailablePropertiesInner


class TestAvailablePropertiesInner(unittest.TestCase):
    """AvailablePropertiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePropertiesInner(self):
        """Test AvailablePropertiesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailablePropertiesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
