"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.availability_get import AvailabilityGet


class TestAvailabilityGet(unittest.TestCase):
    """AvailabilityGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailabilityGet(self):
        """Test AvailabilityGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailabilityGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
