"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_facility_info_amenity_list import InlineResponse2003PropertyFacilityInfoAmenityList
from lodgea-python.model.inline_response2003_property_facility_info_media_list import InlineResponse2003PropertyFacilityInfoMediaList
from lodgea-python.model.inline_response2003_property_facility_info_message_list import InlineResponse2003PropertyFacilityInfoMessageList
globals()['InlineResponse2003PropertyFacilityInfoAmenityList'] = InlineResponse2003PropertyFacilityInfoAmenityList
globals()['InlineResponse2003PropertyFacilityInfoMediaList'] = InlineResponse2003PropertyFacilityInfoMediaList
globals()['InlineResponse2003PropertyFacilityInfoMessageList'] = InlineResponse2003PropertyFacilityInfoMessageList
from lodgea-python.model.inline_response2003_property_facility_info_guest_room_list import InlineResponse2003PropertyFacilityInfoGuestRoomList


class TestInlineResponse2003PropertyFacilityInfoGuestRoomList(unittest.TestCase):
    """InlineResponse2003PropertyFacilityInfoGuestRoomList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyFacilityInfoGuestRoomList(self):
        """Test InlineResponse2003PropertyFacilityInfoGuestRoomList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyFacilityInfoGuestRoomList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
