"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_policy_info_fee_policy_list import InlineResponse2003PolicyInfoFeePolicyList
from lodgea-python.model.inline_response2003_policy_info_tax_policy_list import InlineResponse2003PolicyInfoTaxPolicyList
from lodgea-python.model.inline_response2003_property_cancellation_policy_list import InlineResponse2003PropertyCancellationPolicyList
from lodgea-python.model.inline_response2003_property_guarantee_policy import InlineResponse2003PropertyGuaranteePolicy
from lodgea-python.model.inline_response2003_property_pets_policy import InlineResponse2003PropertyPetsPolicy
globals()['InlineResponse2003PolicyInfoFeePolicyList'] = InlineResponse2003PolicyInfoFeePolicyList
globals()['InlineResponse2003PolicyInfoTaxPolicyList'] = InlineResponse2003PolicyInfoTaxPolicyList
globals()['InlineResponse2003PropertyCancellationPolicyList'] = InlineResponse2003PropertyCancellationPolicyList
globals()['InlineResponse2003PropertyGuaranteePolicy'] = InlineResponse2003PropertyGuaranteePolicy
globals()['InlineResponse2003PropertyPetsPolicy'] = InlineResponse2003PropertyPetsPolicy
from lodgea-python.model.inline_response2003_policy_info import InlineResponse2003PolicyInfo


class TestInlineResponse2003PolicyInfo(unittest.TestCase):
    """InlineResponse2003PolicyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PolicyInfo(self):
        """Test InlineResponse2003PolicyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PolicyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
