"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_policy_info_tax_policy_list import InlineResponse2003PolicyInfoTaxPolicyList


class TestInlineResponse2003PolicyInfoTaxPolicyList(unittest.TestCase):
    """InlineResponse2003PolicyInfoTaxPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PolicyInfoTaxPolicyList(self):
        """Test InlineResponse2003PolicyInfoTaxPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PolicyInfoTaxPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
