"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_address_list import InlineResponse2003PropertyAddressList
globals()['InlineResponse2003PropertyAddressList'] = InlineResponse2003PropertyAddressList
from lodgea-python.model.inline_response2003_property_contact_list import InlineResponse2003PropertyContactList


class TestInlineResponse2003PropertyContactList(unittest.TestCase):
    """InlineResponse2003PropertyContactList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyContactList(self):
        """Test InlineResponse2003PropertyContactList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyContactList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
