"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_cancellation_grace_period import PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod


class TestPropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
