"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_media_list_inner import AvailablePropertiesInner1MediaListInner


class TestAvailablePropertiesInner1MediaListInner(unittest.TestCase):
    """AvailablePropertiesInner1MediaListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePropertiesInner1MediaListInner(self):
        """Test AvailablePropertiesInner1MediaListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailablePropertiesInner1MediaListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
