"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_facility_info_guest_room_list import InlineResponse2003PropertyFacilityInfoGuestRoomList
globals()['InlineResponse2003PropertyFacilityInfoGuestRoomList'] = InlineResponse2003PropertyFacilityInfoGuestRoomList
from lodgea-python.model.inline_response2003_property_facility_info import InlineResponse2003PropertyFacilityInfo


class TestInlineResponse2003PropertyFacilityInfo(unittest.TestCase):
    """InlineResponse2003PropertyFacilityInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyFacilityInfo(self):
        """Test InlineResponse2003PropertyFacilityInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyFacilityInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
