"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2004_pricing_list import InlineResponse2004PricingList
globals()['InlineResponse2004PricingList'] = InlineResponse2004PricingList
from lodgea-python.model.inline_response2004_rate_plan_list import InlineResponse2004RatePlanList


class TestInlineResponse2004RatePlanList(unittest.TestCase):
    """InlineResponse2004RatePlanList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004RatePlanList(self):
        """Test InlineResponse2004RatePlanList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004RatePlanList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
