"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_product_list_inner_policy_info import PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo
from lodgea-python.model.properties_property_id_get200_response_product_list_inner_rate_plan_list_inner import PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner
globals()['PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo'] = PropertiesPropertyIdGet200ResponseProductListInnerPolicyInfo
globals()['PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner'] = PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner
from lodgea-python.model.properties_property_id_get200_response_product_list_inner import PropertiesPropertyIdGet200ResponseProductListInner


class TestPropertiesPropertyIdGet200ResponseProductListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponseProductListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponseProductListInner(self):
        """Test PropertiesPropertyIdGet200ResponseProductListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponseProductListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
