"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_contact_list_inner_address_list_inner import PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner'] = PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner
from lodgea-python.model.properties_property_id_get200_response_property_contact_list_inner import PropertiesPropertyIdGet200ResponsePropertyContactListInner


class TestPropertiesPropertyIdGet200ResponsePropertyContactListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyContactListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyContactListInner(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyContactListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyContactListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
