"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.v1_availability_get_post200_response_rate_plan_list_inner import V1AvailabilityGetPost200ResponseRatePlanListInner
from lodgea-python.model.v1_availability_get_post200_response_room_type_list_inner import V1AvailabilityGetPost200ResponseRoomTypeListInner
from lodgea-python.model.v1_property_get_post200_response_product_list_inner_meal_plan_list_inner import V1PropertyGetPost200ResponseProductListInnerMealPlanListInner
globals()['V1AvailabilityGetPost200ResponseRatePlanListInner'] = V1AvailabilityGetPost200ResponseRatePlanListInner
globals()['V1AvailabilityGetPost200ResponseRoomTypeListInner'] = V1AvailabilityGetPost200ResponseRoomTypeListInner
globals()['V1PropertyGetPost200ResponseProductListInnerMealPlanListInner'] = V1PropertyGetPost200ResponseProductListInnerMealPlanListInner
from lodgea-python.model.v1_availability_get_post200_response import V1AvailabilityGetPost200Response


class TestV1AvailabilityGetPost200Response(unittest.TestCase):
    """V1AvailabilityGetPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AvailabilityGetPost200Response(self):
        """Test V1AvailabilityGetPost200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AvailabilityGetPost200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
