"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner1_geo_location import AvailablePropertiesInner1GeoLocation
globals()['AvailablePropertiesInner1GeoLocation'] = AvailablePropertiesInner1GeoLocation
from lodgea-python.model.available_properties_inner1_geo import AvailablePropertiesInner1Geo


class TestAvailablePropertiesInner1Geo(unittest.TestCase):
    """AvailablePropertiesInner1Geo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePropertiesInner1Geo(self):
        """Test AvailablePropertiesInner1Geo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailablePropertiesInner1Geo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
