"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.property_list import PropertyList


class TestPropertyList(unittest.TestCase):
    """PropertyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertyList(self):
        """Test PropertyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
