"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2001_geo_location import InlineResponse2001GeoLocation
from lodgea-python.model.inline_response2003_property_property_info_accepted_payment_list import InlineResponse2003PropertyPropertyInfoAcceptedPaymentList
from lodgea-python.model.inline_response2003_property_property_info_message_list import InlineResponse2003PropertyPropertyInfoMessageList
globals()['InlineResponse2001GeoLocation'] = InlineResponse2001GeoLocation
globals()['InlineResponse2003PropertyPropertyInfoAcceptedPaymentList'] = InlineResponse2003PropertyPropertyInfoAcceptedPaymentList
globals()['InlineResponse2003PropertyPropertyInfoMessageList'] = InlineResponse2003PropertyPropertyInfoMessageList
from lodgea-python.model.inline_response2003_property_property_info import InlineResponse2003PropertyPropertyInfo


class TestInlineResponse2003PropertyPropertyInfo(unittest.TestCase):
    """InlineResponse2003PropertyPropertyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyPropertyInfo(self):
        """Test InlineResponse2003PropertyPropertyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyPropertyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
