"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.available_properties_inner import AvailablePropertiesInner
globals()['AvailablePropertiesInner'] = AvailablePropertiesInner
from lodgea-python.model.location_search_post200_response import LocationSearchPost200Response


class TestLocationSearchPost200Response(unittest.TestCase):
    """LocationSearchPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationSearchPost200Response(self):
        """Test LocationSearchPost200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocationSearchPost200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
