"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_service_list_inner_operation_time_list_inner import PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner'] = PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
from lodgea-python.model.properties_property_id_get200_response_property_service_list_inner import PropertiesPropertyIdGet200ResponsePropertyServiceListInner


class TestPropertiesPropertyIdGet200ResponsePropertyServiceListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyServiceListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyServiceListInner(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyServiceListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyServiceListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
