"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_pricing_list import InlineResponse2003PricingList
globals()['InlineResponse2003PricingList'] = InlineResponse2003PricingList
from lodgea-python.model.inline_response2003_rate_plan_list import InlineResponse2003RatePlanList


class TestInlineResponse2003RatePlanList(unittest.TestCase):
    """InlineResponse2003RatePlanList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003RatePlanList(self):
        """Test InlineResponse2003RatePlanList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003RatePlanList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
