"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_product_list_inner_rate_plan_list_inner_pricing_list_inner import PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner


class TestPropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner(self):
        """Test PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInnerPricingListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
