"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_product_list_inner_rate_plan_list_inner import PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner
globals()['PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner'] = PropertiesPropertyIdGet200ResponseProductListInnerRatePlanListInner
from lodgea-python.model.properties_property_id_availability_get200_response_availability_list_inner import PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner


class TestPropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner(unittest.TestCase):
    """PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner(self):
        """Test PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
