"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_property_facility_info_message_list import InlineResponse2003PropertyFacilityInfoMessageList


class TestInlineResponse2003PropertyFacilityInfoMessageList(unittest.TestCase):
    """InlineResponse2003PropertyFacilityInfoMessageList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003PropertyFacilityInfoMessageList(self):
        """Test InlineResponse2003PropertyFacilityInfoMessageList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003PropertyFacilityInfoMessageList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
