"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_amenity_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner
from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_media_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_message_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner
from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner


class TestPropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
