"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.properties_property_id_get200_response_property_guest_info import PropertiesPropertyIdGet200ResponsePropertyGuestInfo


class TestPropertiesPropertyIdGet200ResponsePropertyGuestInfo(unittest.TestCase):
    """PropertiesPropertyIdGet200ResponsePropertyGuestInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesPropertyIdGet200ResponsePropertyGuestInfo(self):
        """Test PropertiesPropertyIdGet200ResponsePropertyGuestInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropertiesPropertyIdGet200ResponsePropertyGuestInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
