"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response2003_policy_info import InlineResponse2003PolicyInfo
from lodgea-python.model.inline_response2003_rate_plan_list import InlineResponse2003RatePlanList
globals()['InlineResponse2003PolicyInfo'] = InlineResponse2003PolicyInfo
globals()['InlineResponse2003RatePlanList'] = InlineResponse2003RatePlanList
from lodgea-python.model.inline_response2003_product_list import InlineResponse2003ProductList


class TestInlineResponse2003ProductList(unittest.TestCase):
    """InlineResponse2003ProductList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003ProductList(self):
        """Test InlineResponse2003ProductList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003ProductList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
