"""
    lodgea-python

    LODGEA SDK for python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lodgea-python
from lodgea-python.model.inline_response400_validation_errors import InlineResponse400ValidationErrors


class TestInlineResponse400ValidationErrors(unittest.TestCase):
    """InlineResponse400ValidationErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400ValidationErrors(self):
        """Test InlineResponse400ValidationErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse400ValidationErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
