"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from lodgea-python.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from lodgea-python.exceptions import ApiAttributeError


def lazy_import():
    from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_amenity_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner
    from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_media_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
    from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_message_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner


class PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('room_type_code',): {
            '1': 1,
            '4': 4,
            '5': 5,
            '7': 7,
            '8': 8,
            '9': 9,
            '10': 10,
            '12': 12,
            '13': 13,
            '24': 24,
            '25': 25,
            '26': 26,
            '27': 27,
            '28': 28,
            '29': 29,
            '31': 31,
            '32': 32,
            '33': 33,
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'is_active': (bool,),  # noqa: E501
            'room_id': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'media_list': ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner],),  # noqa: E501
            'room_type_code': (float,),  # noqa: E501
            'is_non_smoking': (bool,),  # noqa: E501
            'amenity_list': ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner],),  # noqa: E501
            'message_list': ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner],),  # noqa: E501
            'max_occupancy': (float,),  # noqa: E501
            'max_adult_occupancy': (float,),  # noqa: E501
            'max_child_occupancy': (float,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'is_active': 'isActive',  # noqa: E501
        'room_id': 'roomId',  # noqa: E501
        'name': 'name',  # noqa: E501
        'media_list': 'mediaList',  # noqa: E501
        'room_type_code': 'roomTypeCode',  # noqa: E501
        'is_non_smoking': 'isNonSmoking',  # noqa: E501
        'amenity_list': 'amenityList',  # noqa: E501
        'message_list': 'messageList',  # noqa: E501
        'max_occupancy': 'maxOccupancy',  # noqa: E501
        'max_adult_occupancy': 'maxAdultOccupancy',  # noqa: E501
        'max_child_occupancy': 'maxChildOccupancy',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, is_active, room_id, name, media_list, room_type_code, is_non_smoking, amenity_list, message_list, max_occupancy, max_adult_occupancy, max_child_occupancy, *args, **kwargs):  # noqa: E501
        """PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner - a model defined in OpenAPI

        Args:
            is_active (bool): Indicates whether the room is active or not.
            room_id (str): The unique identifier for the room.
            name (str): The name of the room.
            media_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner]): A list of media objects for the room.
            room_type_code (float): The unit and room type code.<p>See also <a href=\"#unitand-room-type-codes\">in the appendix</a>.</p>
            is_non_smoking (bool): Indicates whether the room is designated as non-smoking.
            amenity_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner]): A list of amenities provided in the room.
            message_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner]): A list of messages associated with the room.
            max_occupancy (float): The maximum occupancy of the room.
            max_adult_occupancy (float): The maximum number of adults that can occupy the room.
            max_child_occupancy (float): The maximum number of children that can occupy the room.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.is_active = is_active
        self.room_id = room_id
        self.name = name
        self.media_list = media_list
        self.room_type_code = room_type_code
        self.is_non_smoking = is_non_smoking
        self.amenity_list = amenity_list
        self.message_list = message_list
        self.max_occupancy = max_occupancy
        self.max_adult_occupancy = max_adult_occupancy
        self.max_child_occupancy = max_child_occupancy
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, is_active, room_id, name, media_list, room_type_code, is_non_smoking, amenity_list, message_list, max_occupancy, max_adult_occupancy, max_child_occupancy, *args, **kwargs):  # noqa: E501
        """PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInner - a model defined in OpenAPI

        Args:
            is_active (bool): Indicates whether the room is active or not.
            room_id (str): The unique identifier for the room.
            name (str): The name of the room.
            media_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner]): A list of media objects for the room.
            room_type_code (float): The unit and room type code.<p>See also <a href=\"#unitand-room-type-codes\">in the appendix</a>.</p>
            is_non_smoking (bool): Indicates whether the room is designated as non-smoking.
            amenity_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerAmenityListInner]): A list of amenities provided in the room.
            message_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMessageListInner]): A list of messages associated with the room.
            max_occupancy (float): The maximum occupancy of the room.
            max_adult_occupancy (float): The maximum number of adults that can occupy the room.
            max_child_occupancy (float): The maximum number of children that can occupy the room.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.is_active = is_active
        self.room_id = room_id
        self.name = name
        self.media_list = media_list
        self.room_type_code = room_type_code
        self.is_non_smoking = is_non_smoking
        self.amenity_list = amenity_list
        self.message_list = message_list
        self.max_occupancy = max_occupancy
        self.max_adult_occupancy = max_adult_occupancy
        self.max_child_occupancy = max_child_occupancy
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
