"""
    lodgea-python

    LODGEA SDK for Python. Check out https://docs.lodgea.io for more information.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support@lodgea.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from lodgea-python.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from lodgea-python.exceptions import ApiAttributeError


def lazy_import():
    from lodgea-python.model.available_properties_inner1_geo import AvailablePropertiesInner1Geo
    from lodgea-python.model.properties_property_id_get200_response_property_award_list_inner import PropertiesPropertyIdGet200ResponsePropertyAwardListInner
    from lodgea-python.model.properties_property_id_get200_response_property_cancellation_grace_period import PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
    from lodgea-python.model.properties_property_id_get200_response_property_contact_list_inner import PropertiesPropertyIdGet200ResponsePropertyContactListInner
    from lodgea-python.model.properties_property_id_get200_response_property_facility_info import PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
    from lodgea-python.model.properties_property_id_get200_response_property_facility_info_guest_room_list_inner_media_list_inner import PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
    from lodgea-python.model.properties_property_id_get200_response_property_guest_info import PropertiesPropertyIdGet200ResponsePropertyGuestInfo
    from lodgea-python.model.properties_property_id_get200_response_property_policy_list_inner import PropertiesPropertyIdGet200ResponsePropertyPolicyListInner
    from lodgea-python.model.properties_property_id_get200_response_property_property_info import PropertiesPropertyIdGet200ResponsePropertyPropertyInfo
    from lodgea-python.model.properties_property_id_get200_response_property_record_created import PropertiesPropertyIdGet200ResponsePropertyRecordCreated
    from lodgea-python.model.properties_property_id_get200_response_property_record_modified import PropertiesPropertyIdGet200ResponsePropertyRecordModified
    from lodgea-python.model.properties_property_id_get200_response_property_service_list_inner import PropertiesPropertyIdGet200ResponsePropertyServiceListInner
    globals()['AvailablePropertiesInner1Geo'] = AvailablePropertiesInner1Geo
    globals()['PropertiesPropertyIdGet200ResponsePropertyAwardListInner'] = PropertiesPropertyIdGet200ResponsePropertyAwardListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod'] = PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod
    globals()['PropertiesPropertyIdGet200ResponsePropertyContactListInner'] = PropertiesPropertyIdGet200ResponsePropertyContactListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfo'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfo
    globals()['PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner'] = PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyGuestInfo'] = PropertiesPropertyIdGet200ResponsePropertyGuestInfo
    globals()['PropertiesPropertyIdGet200ResponsePropertyPolicyListInner'] = PropertiesPropertyIdGet200ResponsePropertyPolicyListInner
    globals()['PropertiesPropertyIdGet200ResponsePropertyPropertyInfo'] = PropertiesPropertyIdGet200ResponsePropertyPropertyInfo
    globals()['PropertiesPropertyIdGet200ResponsePropertyRecordCreated'] = PropertiesPropertyIdGet200ResponsePropertyRecordCreated
    globals()['PropertiesPropertyIdGet200ResponsePropertyRecordModified'] = PropertiesPropertyIdGet200ResponsePropertyRecordModified
    globals()['PropertiesPropertyIdGet200ResponsePropertyServiceListInner'] = PropertiesPropertyIdGet200ResponsePropertyServiceListInner


class PropertiesPropertyIdGet200ResponseProperty(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'code': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'record_created': (PropertiesPropertyIdGet200ResponsePropertyRecordCreated,),  # noqa: E501
            'record_modified': (PropertiesPropertyIdGet200ResponsePropertyRecordModified,),  # noqa: E501
            'property_info': (PropertiesPropertyIdGet200ResponsePropertyPropertyInfo,),  # noqa: E501
            'award_list': ([PropertiesPropertyIdGet200ResponsePropertyAwardListInner],),  # noqa: E501
            'contact_list': ([PropertiesPropertyIdGet200ResponsePropertyContactListInner],),  # noqa: E501
            'media_list': ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner],),  # noqa: E501
            'published': (bool,),  # noqa: E501
            'policy_list': ([PropertiesPropertyIdGet200ResponsePropertyPolicyListInner],),  # noqa: E501
            'service_list': ([PropertiesPropertyIdGet200ResponsePropertyServiceListInner],),  # noqa: E501
            'guest_info': (PropertiesPropertyIdGet200ResponsePropertyGuestInfo,),  # noqa: E501
            'facility_info': (PropertiesPropertyIdGet200ResponsePropertyFacilityInfo,),  # noqa: E501
            'geo': ({str: (AvailablePropertiesInner1Geo,)},),  # noqa: E501
            'uri': (str,),  # noqa: E501
            'cancellation_grace_period': (PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'code': 'code',  # noqa: E501
        'name': 'name',  # noqa: E501
        'record_created': 'recordCreated',  # noqa: E501
        'record_modified': 'recordModified',  # noqa: E501
        'property_info': 'propertyInfo',  # noqa: E501
        'award_list': 'awardList',  # noqa: E501
        'contact_list': 'contactList',  # noqa: E501
        'media_list': 'mediaList',  # noqa: E501
        'published': 'published',  # noqa: E501
        'policy_list': 'policyList',  # noqa: E501
        'service_list': 'serviceList',  # noqa: E501
        'guest_info': 'guestInfo',  # noqa: E501
        'facility_info': 'facilityInfo',  # noqa: E501
        'geo': 'geo',  # noqa: E501
        'uri': 'uri',  # noqa: E501
        'cancellation_grace_period': 'cancellationGracePeriod',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, code, name, record_created, record_modified, property_info, award_list, contact_list, media_list, published, policy_list, service_list, *args, **kwargs):  # noqa: E501
        """PropertiesPropertyIdGet200ResponseProperty - a model defined in OpenAPI

        Args:
            code (str): The properties unique identifier.
            name (str): The properties name.
            record_created (PropertiesPropertyIdGet200ResponsePropertyRecordCreated):
            record_modified (PropertiesPropertyIdGet200ResponsePropertyRecordModified):
            property_info (PropertiesPropertyIdGet200ResponsePropertyPropertyInfo):
            award_list ([PropertiesPropertyIdGet200ResponsePropertyAwardListInner]): A list of the ratings available for this property.
            contact_list ([PropertiesPropertyIdGet200ResponsePropertyContactListInner]): A contact with a profile type and a list of addresses
            media_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner]): A list of media objects for the property.
            published (bool): Indicates whether the policy has been published or not.
            policy_list ([PropertiesPropertyIdGet200ResponsePropertyPolicyListInner]): A list of policies associated with the property.
            service_list ([PropertiesPropertyIdGet200ResponsePropertyServiceListInner]): A list of objects each describing an available service, its pricing and its availability.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            guest_info (PropertiesPropertyIdGet200ResponsePropertyGuestInfo): [optional]  # noqa: E501
            facility_info (PropertiesPropertyIdGet200ResponsePropertyFacilityInfo): [optional]  # noqa: E501
            geo ({str: (AvailablePropertiesInner1Geo,)}): An object containing language codes as keys and objects describing the properties geographical location as values.. [optional]  # noqa: E501
            uri (str): A unique identifier for the accommodation.. [optional]  # noqa: E501
            cancellation_grace_period (PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.code = code
        self.name = name
        self.record_created = record_created
        self.record_modified = record_modified
        self.property_info = property_info
        self.award_list = award_list
        self.contact_list = contact_list
        self.media_list = media_list
        self.published = published
        self.policy_list = policy_list
        self.service_list = service_list
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, code, name, record_created, record_modified, property_info, award_list, contact_list, media_list, published, policy_list, service_list, *args, **kwargs):  # noqa: E501
        """PropertiesPropertyIdGet200ResponseProperty - a model defined in OpenAPI

        Args:
            code (str): The properties unique identifier.
            name (str): The properties name.
            record_created (PropertiesPropertyIdGet200ResponsePropertyRecordCreated):
            record_modified (PropertiesPropertyIdGet200ResponsePropertyRecordModified):
            property_info (PropertiesPropertyIdGet200ResponsePropertyPropertyInfo):
            award_list ([PropertiesPropertyIdGet200ResponsePropertyAwardListInner]): A list of the ratings available for this property.
            contact_list ([PropertiesPropertyIdGet200ResponsePropertyContactListInner]): A contact with a profile type and a list of addresses
            media_list ([PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner]): A list of media objects for the property.
            published (bool): Indicates whether the policy has been published or not.
            policy_list ([PropertiesPropertyIdGet200ResponsePropertyPolicyListInner]): A list of policies associated with the property.
            service_list ([PropertiesPropertyIdGet200ResponsePropertyServiceListInner]): A list of objects each describing an available service, its pricing and its availability.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            guest_info (PropertiesPropertyIdGet200ResponsePropertyGuestInfo): [optional]  # noqa: E501
            facility_info (PropertiesPropertyIdGet200ResponsePropertyFacilityInfo): [optional]  # noqa: E501
            geo ({str: (AvailablePropertiesInner1Geo,)}): An object containing language codes as keys and objects describing the properties geographical location as values.. [optional]  # noqa: E501
            uri (str): A unique identifier for the accommodation.. [optional]  # noqa: E501
            cancellation_grace_period (PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.code = code
        self.name = name
        self.record_created = record_created
        self.record_modified = record_modified
        self.property_info = property_info
        self.award_list = award_list
        self.contact_list = contact_list
        self.media_list = media_list
        self.published = published
        self.policy_list = policy_list
        self.service_list = service_list
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
